name: 定时采集

on:
  schedule:
    - cron: '25 10,22 * * *'
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest  # 在 Ubuntu 上运行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Run main.sh
        id: main_script
        run: |
          chmod +x ./main.sh
          ./main.sh || echo "Main script failed with exit code $?"

      - name: Get recent workflow runs
        id: get_runs
        if: failure() # 如果 main.sh 失败才执行
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GITHUB_TOKEN"
          gh run list --workflow=main.yml --repo ${{ github.repository }} --limit 10 --json conclusion
